### ISSUE TITLE
Would it be possible to bundle dependencies into renderer.js

### ISSUE THREAD

**Issue by juanstiza** [ptrdom/scalajs-electron-quick-start#2]
Hi! I have been playing around with this project a bit and I was wondering: is it possible to bundle dependencies (like react) into `renderer.js`?

I am just getting started with scala.js and wanted to figure that out. I did try to add the `scala-js-bundler` plugin, but I have no clue how to integrate it with `ElectronPlugin`.

If you have any pointers, that would be great.

Thanks!

**Comment by ptrdom** [comment]
This plugin is very barebones conversion to Scala.js, for more complex projects I would advise to checkout https://github.com/ptrdom/scalajs-vite#electron. This is a plugin based on [Vite](https://vitejs.dev/), it is fully functional, but I do not like how slow is the bundling with Vite, that is why I am still working on https://github.com/ptrdom/scalajs-esbuild. This [esbuild](https://esbuild.github.io/) based plugin has really amazing bundling performance, but I have not yet implemented the Electron plugin for it.

**Comment by juanstiza** [comment]
Yup, I am currently checking it out! Thanks!!
